id: PD73539D4
initial_creation_type: input
source_metadata:
  title: 'MSV 3,01: Bhikṣuṇīvibhaṅga'
  language: bo
  volumes:
    45352f5a25bf493b881638d03028198b:
      title: Bhikṣuṇīvibhaṅga
      base_file: Bhikṣuṇīvibhaṅga.txt
      work_id: W66D282FB
  chapter_to_tile: {}
created_at: '2022-03-01T22:50:51.331080'
last_modified_at: '2022-03-01T22:50:51.331090'
